tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "moncho/dry"
tap "mgrubb/utils"
cask_args appdir: "/Applications"

brew "coreutils"
brew "gnu-tar"
brew "git"
brew "git-flow-avh"
brew "git-utils"
brew "jq"
brew "neovim"
brew "pyenv"
brew "rbenv"
brew "tmux"
brew "wget"
brew "curl"
brew "bash"
brew "go"
brew "scala"
brew "sbt"

brew "mgrubb/utils/apg", args: ["HEAD"]
brew "moncho/dry/dry"

cask "docker"
cask "hammerspoon"
cask "vimr"
cask "postgres"
cask "tiddly"
cask "dropbox"
cask "iterm2"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vagrant"
cask "pastebot"
cask "sourcetree"
cask "wireshark"
cask "bartender"
cask "bettertouchtool"
cask "istat-menus"
cask "lastpass"
cask "balenaetcher"

mas "Sequence Diagram", id: 1195426709
mas "The Unarchiver", id: 425424353
mas "Kaleidoscope", id: 587512244
mas "HyperDock", id: 449830122
