" An example for a gvimrc file.
" The commands in this are executed when the GUI is started.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2001 Sep 02
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.gvimrc
"	      for Amiga:  s:.gvimrc
"  for MS-DOS and Win32:  $VIM\_gvimrc
"	    for OpenVMS:  sys$login:.gvimrc

" Make external commands work through a pipe instead of a pseudo-tty
"set noguipty

" set the X11 font to use
" set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1
set mousehide		" Hide the mouse when typing text

" Make shift-insert work like in Xterm
map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

" Only do this for Vim version 5.0 and later.
if version >= 500

  " I like highlighting strings inside C comments
  let c_comment_strings=1

  " Switch on syntax highlighting if it wasn't on yet.
  if !exists("syntax_on")
    syntax on
  endif

  " Switch on search pattern highlighting.
  set hlsearch

  " For Win32 version, have "K" lookup the keyword in a help file
  "if has("win32")
  "  let winhelpfile='windows.hlp'
  "  map K :execute "!start winhlp32 -k <cword> " . winhelpfile <CR>
  "endif

  " Set nice colors
  " background for normal text is light grey
  " Text below the last line is darker grey
  " Cursor is green, Cyan when ":lmap" mappings are active
  " Constants are not underlined but have a slightly lighter background
  highlight Normal guibg=grey90
  highlight Cursor guibg=Green guifg=NONE
  highlight lCursor guibg=Cyan guifg=NONE
  highlight NonText guibg=grey80
  highlight Constant gui=NONE guibg=grey95
  highlight Special gui=NONE guibg=grey95

endif

highlight Visual guibg=grey80
"set guifont=Monaco:h10
"set guifont=Consolas:h18
"set guifont=Inconsolata:h18
"set guifont=Envy\ Code\ R:h16
set guifont=AnonymousPro:h16
set linespace=4
" colorscheme myvibrantink
colorscheme mg_symfony

" hide the toolbar by default
set guioptions-=T

" This will move the focus back to the terminal window when started 
" from the terminal.  For this to work, set the following in the shell
" VIMINIT="--cmd 'let b:fromterminal=1|so $HOME/.vimrc'"
" Set g:terminal_program to the name of the terminal program you are using
" Set appswith_path to the location of the appswitch command
"let g:terminal_program = "iTerm"
"let g:appswitch_path = "/usr/local/bin/appswitch"
"runtime switcher.vim
"so $HOME/.vim/switcher.vim
"autocmd VimLeave * call SwitchToTerm()

